### ISSUE TITLE
Install documentation outdated

### ISSUE THREAD

**Issue by mrenvoize** [tokuhirom/plenv#112]
github no longer appears to support the git protocol, so the install documentation would sensibly be switched to either the ssh or https uri ;)

**Comment by syohex** [comment]
#113 has been merged. Please close this issue.

**Comment by miyagawa** [comment]
github does support the git protocol, by the way - it's just you need to have an SSH key-pairs to be able to clone it.

**Comment by mrenvoize** [comment]
Interesting, I thought they'd got rid of git protocol support, can't see it in those pointed to docs either.. only subversion, https or ssh.

No matter, the https protocol seems to be the most widely available so I'm glad the patch got made, many thanks :)

**Comment by miyagawa** [comment]
Yeah it's not mentioned in the docs since it's not secure and some users will see problems in a blocked port situation and github doesn't want to advertise it, but it definitely works otherwise.
