### ISSUE TITLE
readlink search broken on some systems

### ISSUE THREAD

**Issue by patzim** [tokuhirom/plenv#115]
Commit 6dadd1c606856990dcc causes the following error on one of my systems when calling `plenv`.

    ~/.plenv/bin/plenv: line 15: /dev/fd/62: No such file or directory
    plenv: cannot find readlink - are you missing GNU coreutils?

Reverting that commit fixes the issue. `/dev/fd` is a broken symlink on that machine.

**Comment by syohex** [comment]
I suppose process substitution does not work on your machine.

Could you tell us your environment ? 
- OS ?
- bash version ?
- etc

I cannot reproduce your issue on my MacOSX 10.11.2, bash 3.2 and Ubuntu 15.10, bash 4.3.

**Comment by patzim** [comment]
The machine is a server I have no admin rights on.

    $ uname -a
    Linux dgws15s3-2-27da.ispgateway.de 3.2.60-grsec-x86_64 #9 SMP Fri Jun 27 12:58:46 CEST 2014 x86_64 GNU/Linux
    $ cat /etc/gentoo-release                                                                                  
    Gentoo Base System release 2.2
    $ bash --version
    GNU bash, version 4.2.53(1)-release (i686-pc-linux-gnu)
    Copyright (C) 2011 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    
    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    $ ls -lh /dev/fd
    lrwxrwxrwx 1 root root 13 Jan  1 05:14 /dev/fd -> /proc/self/fd
    $ mount
    /dev/md1 on / type ext3 (rw)

`/proc` is empty.
I start to suspect that the machine is simply set up wrong...

**Comment by syohex** [comment]
Please try again after executing following command.

```
# mount -t proc none /proc
```

And add its setting to `/etc/fstab`.

See also
- https://wiki.gentoo.org/wiki/Procfs

**Comment by syohex** [comment]
Please report your server administrator about mounting procfs. I think all Linux system should mount procfs, devtmpfs, sysfs. And process substitution is bash feature so it is no problems about using it.
