### ISSUE TITLE
plenv install-cpanm  seg faults 

### ISSUE THREAD

**Issue by itcharlie** [tokuhirom/plenv#117]
I am running the latest version of plenv and perl-build but I am unable to install cpanm for perl 5.22.1.
Please advise.

```
cgonzalez@ubuntu:~$ plenv
plenv 2.1.1-56-g626847c

cgonzalez@ubuntu:~$ plenv versions
  system
* 5.22.1 (set by /home/cgonzalez/.perl-version)
cgonzalez@ubuntu:~$ plenv install-cpanm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314    0   314    0     0    853      0 --:--:-- --:--:-- --:--:--   853
100  296k  100  296k    0     0   496k      0 --:--:-- --:--:-- --:--:--  496k
/home/cgonzalez/.plenv/libexec/plenv-install-cpanm: line 65: 17951 Done                    curl ${PLENV_INSTALL_CPANM} -L http://cpanmin.us/
     17952 Segmentation fault      (core dumped) | plenv exec perl - ExtUtils::MakeMaker App::cpanminus
```

**Comment by miyagawa** [comment]
* Does it only happen with 5.22.1?
* If you run `curl -L http://cpanmin.us` do you get the right perl source code? If not, try also with https?

**Comment by itcharlie** [comment]
Also happens on a perl build version 5.20.3

Yes I get the correct cpanm code when running curl -L http://cpanmin.us

**Comment by syohex** [comment]
I cannot reproduce on my Ubuntu. Could you show us backtrace ?

```
% plenv install 5.22.1 -DDEBUGGING=-g
% plenv global 5.22.1
% ulimit -c unlimited
% plenv install-cpanm
# 'core' file may be generated
# You need to install gdb by 'sudo apt-get install gdb' if you didn't install gdb yet.
% gdb ~/.plenv/versions/5.22.1/bin/perl5.22.1 core
(gdb) backtrace
```

**Comment by shoichikaji** [comment]
Can you attach ~/.cpanm/build.log when running `plenv install-cpanm`?

**Comment by miyagawa** [comment]
@itcharlie do you have local::lib or some PERL5LIB environment variables set? I suspect you have that variable set and you're trying to load the binary of different perl versions and hence crashes.

If that's the case, remove the local::lib env variables or PERL5LIB and start over.

**Comment by itcharlie** [comment]
I am so sorry everyone. I had an entry in my .bashrc  file that modified the PERL5LIB Path. I removed the entry and now I am able to run 'plenv install-cpanm'. This is a non issue so marking as such.

cgonzalez@ubuntu:~$ plenv install-cpanm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   314    0   314    0     0    857      0 --:--:-- --:--:-- --:--:--   857
100  296k  100  296k    0     0   414k      0 --:--:-- --:--:-- --:--:-- 4797k
--> Working on ExtUtils::MakeMaker
Fetching http://www.cpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.10.tar.gz ... OK
Configuring ExtUtils-MakeMaker-7.10 ... OK
Building and testing ExtUtils-MakeMaker-7.10 ... OK
Successfully installed ExtUtils-MakeMaker-7.10 (upgraded from 6.98)
--> Working on App::cpanminus
Fetching http://www.cpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-1.7040.tar.gz ... OK
Configuring App-cpanminus-1.7040 ... OK
Building and testing App-cpanminus-1.7040 ... OK
Successfully installed App-cpanminus-1.7040
2 distributions installed
cgonzalez@ubuntu:~$ plenv versions
  system
* 5.20.3 (set by /home/cgonzalez/.perl-version)
  5.21.11
  5.22.1
