### ISSUE TITLE
Error when initializing through a fish shell

### ISSUE THREAD

**Issue by eugenesvk** [tokuhirom/plenv#118]
I've recently installed `fish` shell and now can't initialize `plenv` (installed both via `Homebrew`). I'm using the following command in my `config.fish`:
`status --is-interactive; and . (plenv init -|psub)`

However, I get the following error:
```
'case' builtin not inside of switch block
/var/folders/y9/sgzncbj919d9gsvjtz2rnt_40000gn/T//.psub.R84ki3X3kk (line 9):   case "$command" in
                                                                               ^
from sourcing file /var/folders/y9/sgzncbj919d9gsvjtz2rnt_40000gn/T//.psub.R84ki3X3kk
	called on line 151 of file /usr/local/Cellar/fish/2.2.0/share/fish/config.fish

in function '.'
	called on standard input

source: Error while reading file '/var/folders/y9/sgzncbj919d9gsvjtz2rnt_40000gn/T//.psub.R84ki3X3kk'
```

FYI line 151 of file `/usr/local/Cellar/fish/2.2.0/share/fish/config.fish` is
`		source $argv`

Other virtualenvs work just fine with exactly the same initialization command syntax (`rbenv` and `pyenv`).
Any ideas on why that is happening?

P.S.
Sorry, should've mentioned that it's on `OS X 10.11.2`, `fish 2.2.0`, also not working with `2.2.0-542-g4b2495f` installed from HEAD.

**Comment by brxfork** [comment]
Something to check: as you can see in manual, the installation process is different depending your shell. See note for zsh users: $(plenv init - zsh)
It's just an hypothesis...

**Comment by eugenesvk** [comment]
@brxfork what specifically do you propose to check? I'm already using a init command customized for `fish`

**Comment by syohex** [comment]
I cannot reproduce this issue on my Ubuntu with fish 2.2.0.

**Comment by brxfork** [comment]
@eugenesvk you could try "plenv init - fish" (see libexev/plenv-init file). if I'm wrong, excuse me for the noise.

**Comment by brxfork** [comment]
homebrew formula (https://github.com/Homebrew/homebrew/blob/master/Library/Formula/plenv.rb) refers to https://github.com/tokuhirom/plenv/archive/2.1.1.tar.gz
...but this archive contains 2.1.0 files (without "fish" integration)
`plenv --version` => `plenv 2.1.0`

**Comment by syohex** [comment]
Ah, plenv should add new tag and update homebrew formula.

**Comment by eugenesvk** [comment]
@brxfork this command outputs a wrong suggestion to 
```
# Load plenv automatically by adding
# the following to your profile:

eval "$(plenv init -)"
```
However, your second suggestion is spot on! I've installed homebrew formula from head and now the `status --is-interactive; and . (plenv init -|psub)` command initializes plenv correctly and adds shims to PATH.
Thank you!

**Comment by syohex** [comment]
I have tagged `2.2.0` and I'm creating PR for homebrew.

https://github.com/syohex/homebrew/commit/c6f1dd7d8ddd49feadd745c4ae4c22117f0b683d

I have no Mac machine at hand now. I'll test tonight and send PR.

**Comment by syohex** [comment]
@eugenesvk @brxfork `plenv` of homebrew has been updated. Please try again after `brew update`.

**Comment by eugenesvk** [comment]
@syohex thanks, the update works as well.
