### ISSUE TITLE
install-cpanm for "system" version?

### ISSUE THREAD

**Issue by sergeyromanov** [tokuhirom/plenv#123]
I'd like to be able to do
```
$ plenv global system
$ plenv install-cpanm
```
Right now the second command shows a `cpanm` warning banner and installs it as _~/perl5/bin/cpanm_, which is effectively invisible to `plenv`:
```
$ plenv which cpanm
plenv: cpanm: command not found
```

**Comment by Grinnz** [comment]
You usually need root privileges to install to the system perl, which is probably what the cpanm warning was about. Normally I would recommend not installing anything to the system perl except via the package manager or a local::lib, but App::cpanminus is an exception that should install fine.
`wget -qO - https://cpanmin.us | /usr/bin/perl - --sudo App::cpanminus`
You can also just set up a local::lib for the system perl with https://github.com/miyagawa/plenv-contrib plenv lib and plenv use, so you can install any modules there.

**Comment by syohex** [comment]
@Grinnz Thanks for comments.

@sergeyromanov Please try @Grinnz's ways.
