### ISSUE TITLE
chruby approach?

### ISSUE THREAD

**Issue by rnkn** [tokuhirom/plenv#130]
I'm just curious, would the approach taken with [chruby](https://github.com/postmodern/chruby) work for plenv i.e. without resorting to shims?

**Comment by tokuhirom** [comment]
What's the advantage?

**Comment by rnkn** [comment]
No need to shim executables. More minimal.

**Comment by tokuhirom** [comment]
okay, i see. but there's no motivation to do it. you can implement chperl.

**Comment by rnkn** [comment]
I was considering it. I'm certainly out of my depth. Do you think the Perl installation is similar enough to Ruby? I guess I can follow your lead with rbenv → plenv.
