### ISSUE TITLE
Install to a specific path?

### ISSUE THREAD

**Issue by ggl** [tokuhirom/plenv#132]
Is there any way to install perl versions to a specific path so that one would be able to use them system wide? I am now installing to ~/.plenv/versions which is a symlink to /opt/perl to achieve this.

**Comment by skaji** [comment]
Why don't you use https://github.com/tokuhirom/Perl-Build directly?

**Comment by syohex** [comment]
@skaji Thanks for comment.

@ggl 

> Is there any way to install perl versions to a specific path so that one would be able to use them system wide?

No. plenv manages perl in personal space without administrator permission. You should use Perl-Build or similar tools(like [xbuild](https://github.com/tagomoris/xbuild)) for your purpose.
