### ISSUE TITLE
[error on macos] plenv install --list 

### ISSUE THREAD

**Issue by muenalan** [tokuhirom/plenv#144]
Either install just now with 'brew' or via git, got same bug:

dyld: lazy symbol binding failed: Symbol not found: _Perl_Gthr_key_ptr
  Referenced from: /opt/local/lib/perl5/vendor_perl/5.12.4/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: flat namespace

dyld: Symbol not found: _Perl_Gthr_key_ptr
  Referenced from: /opt/local/lib/perl5/vendor_perl/5.12.4/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: flat namespace

Abort trap: 6

**Comment by muenalan** [comment]
Found the solution here: "https://github.com/linode/cli/issues/7", "vmatekole commented on Oct 5, 2015":

"After reviewing my PATH more carefully, /usr/bin had not been set as priority over /opt/local/bin. All is working now!"

Seems there are two perl's installed (dunno), and the default one is broken.

**Comment by skaji** [comment]
* Please show us the output of `perl -V`.
* Can you update perl-build and try `plenv install --list` again?
    ```
    cd $(plenv root)/plugins/perl-build
    git pull origin master
    plenv install --list
    ```

**Comment by skaji** [comment]
If you find the solution, then you can close this issue:)

**Comment by muenalan** [comment]
SOLVED: perl -V showed an odd entry in PERL5LIB, that was not supposed to be there (perl 5.18 is currently the default perl, why 5.12.4 ?). 

#export PERL5LIB=/opt/local/lib/perl5/vendor_perl/5.12.4/darwin-thread-multi-2level

removed it, and now its working.
