### ISSUE TITLE
plenv shims fail on non-interactive ssh session

### ISSUE THREAD

**Issue by abraxxa** [tokuhirom/plenv#146]
since the ac7a13bc2079e5010c4fc93c05501827c54fcc0c the shim scripts fail on non-interactive ssh sessions (Ansible here) because plenv in line 7 isn't in the path.

**Comment by krautcat** [comment]
Hm, my commits shouldn't change this behaviour.

Can you articulate where you see bugs in my code?

**Comment by abraxxa** [comment]
This line https://github.com/tokuhirom/plenv/commit/ac7a13bc2079e5010c4fc93c05501827c54fcc0c#diff-4e72c7ded2beb5e5873ba51642dee8c8R24 ends up in line 7 of each shim file and tries to run 'plenv' without an absolute path. A non-interactive session doesn't source neither the system nor the user profile so $PATH doesn't include the directory where 'plenv' is located and the shim script fails.

**Comment by abraxxa** [comment]
Thanks!
