### ISSUE TITLE
Segmentation fault: 11 on  plenv install -l

### ISSUE THREAD

**Issue by gvlamadrid** [tokuhirom/plenv#151]
Hi, when i try to install a version of perl or list versions to install `plenv install -l` 
return `Segmentation fault: 11`.
Any I idea?

```
macOS 10.13.6 (17G65)
plenv 2.3.0 (installed using brew)
```
txs a lot! 

P.D. the new version `2.3.0` still return `2.2.0` on  `plenv -v`

**Comment by gvlamadrid** [comment]
My solution not use `brew install perl-build` use `https://github.com/tokuhirom/Perl-Build#install-as-plenv-plugin-recommended`

**Comment by syohex** [comment]
I cannot reproduce and this issue was already fixed. (Homebrew version issue is also fixed)
