### ISSUE TITLE
Plenv to control additional Perl lib paths (PERL5LIB env var?)

### ISSUE THREAD

**Issue by mikkoi** [tokuhirom/plenv#164]
I work with several distributions which have interdependencies. There are, for example, `service-server`, `service-client` and `service-common`. The last contains packages user by both server and client side code. I normally keep these in parallel directories. When I run tests (`prove`) or scripts in either dir `service-server` or dir `service-client`, I need to add `../service-common/lib` to env var PERL5LIB (or call `perl -I../service-common/lib`.

Could plenv take care of this? Perhaps there could be file `.perl-libdirs` next to file `.perl-version`? This file would use PERL5LIB syntax: `dir:other_dir`.

**Comment by mikkoi** [comment]
I created a pull request for a possible solution.

**Comment by mikkoi** [comment]
Instead of changing plenv-exec, could the same thing be done with the hooks?

**Comment by skaji** [comment]
You can create your own plugins.
See, for example, https://github.com/miyagawa/plenv-contrib

**Comment by mikkoi** [comment]
@skaji Thanks. I used plenv-contrib as a model but mine is more complicated because it needs to change the way plenv-exec works.

**Comment by skaji** [comment]
I see.

**Comment by mikkoi** [comment]
Where can I find instructions on how to use the hooks?

**Comment by mikkoi** [comment]
Implemented as a plugin and hook in https://github.com/mikkoi/plenv-libdirs
