### ISSUE TITLE
failure when attempting to install any Perl version on macOS Big Sur

### ISSUE THREAD

**Issue by eprislac** [tokuhirom/plenv#170]
```
*** Unexpected product version 11.0.
***
*** Try running sw_vers and see what its ProductVersion says.
```

output of sw_vers:
```
ProductName:	macOS
ProductVersion:	11.0.1
BuildVersion:	20B50
```

**Comment by syohex** [comment]
https://github.com/Perl/perl5/pull/17946
 
See :arrow_up: . The configure script in older Perl except blead version cannot handle macOS version 11.

**Comment by skaji** [comment]
Make sure you use clang 12.0.0.
```
❯ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
If not, re-install xcode.

**Comment by eprislac** [comment]
yup, using clang 12.0.0 (this is on a brand new Macbook pro with macOS 11.0.1 Big Sur)
```
 ~ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by eprislac** [comment]
```
~ perl-build --version
1.31
``

**Comment by KrisGray** [comment]
I have exactly the same problem. I have the latest clang and the latest perl-build.

**Comment by garu** [comment]
FWIW, 5.32.1 is patched for Big Sur and installs on plenv without any issues. The older ones still fail, though.

I think this is an issue with Devel::PatchPerl (which is used by plenv/perl-build), not plenv itself. I've [opened an issue](https://github.com/bingos/devel-patchperl/issues/54) there and we can follow along to see if there's anything that should be done on the plenv side (other than updating to the latest version of Devel::PatchPerl).

Cheers!

**Comment by skaji** [comment]
I was able to build perl 5.8.3 ~ 5.32.1 (arm64 binary) on MacBook Pro (13-inch, M1, 2020), macOS Big Sur.

**Comment by garu** [comment]
> I was able to build perl 5.8.3 ~ 5.32.1 (arm64 binary) on MacBook Pro (13-inch, M1, 2020), macOS Big Sur.

Hey Kajisan! Indeed, perl-build's homebrew formula was updated from 1.31 to 1.32 and now it works perfectly \o/

I think this issue can be closed now. To anyone who finds it, try this:

`brew update && brew upgrade`

And make sure you're using "perl-build" v1.32 or higher.
