### ISSUE TITLE
No problem to install-cpanm, but failed to find cpanm command

### ISSUE THREAD

**Issue by yong9900** [tokuhirom/plenv#175]
on RedHat 7:

```
[mzhao@mzhao ~]$ plenv global
5.34.0
[mzhao@mzhao ~]$ plenv install-cpanm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  295k  100  295k    0     0  11.4M      0 --:--:-- --:--:-- --:--:-- 11.5M
App::cpanminus is up to date. (1.7044)
[mzhao@mzhao ~]$ plenv which cpanm
plenv: cpanm: command not found
[mzhao@mzhao ~]$ plenv rehash
[mzhao@mzhao ~]$ plenv which cpanm
plenv: cpanm: command not found
```

under my home directory, .cpanm is created, the log file created there mentioned "App::cpanminus is up to date. (1.7044)"
 
Any hint why?

**Comment by yong9900** [comment]
Sorry, looks this is due to my shell env variables, the problem is solved once I did following:
```
[mzhao@mzhao bin]$ unset PERL5LIB PERL_LOCAL_LIB_ROOT PERL_MB_OPT PERL_MM_OPT
```

**Comment by Grinnz** [comment]
A better way to unset those properly is to deactivate your local::lib (`eval $(perl -Mlocal::lib=--deactivate-all)` and ensure your bash profile is not activating one. user-wide local::lib is not compatible with plenv, you must use https://github.com/miyagawa/plenv-contrib to manage local::lib within a perl.

**Comment by yong9900** [comment]
Hi @Grinnz Thanks for the information. I am a newbie on Perl, not quite understand the effect of local::lib. I need to use the system Perl from time to time on my workstation to do some old stuff (the Perl variables was set up for it), but at the same time, I want to use plenv for my new project.  I guess I will just set/unset perl variables when working on different projects?

**Comment by Grinnz** [comment]
You can create a plenv compatible local::lib for the system perl with plenv-contrib, though it doesn't work quite right and you have to `plenv shell system` before `plenv use system@locallibname` works correctly - this spawns a subshell with this local::lib active.

**Comment by Grinnz** [comment]
Otherwise you can use local::lib itself to activate and deactivate as shown in the local::lib docs rather than manually setting vars. But be careful to only activate it when plenv is set to system perl.

**Comment by yong9900** [comment]
@Grinnz Thanks for the explanation. I like your last comment, it's simpler to use my plenv or system Perl. Thanks!
