### ISSUE TITLE
plenv shell  " no such command " error in Ubuntu.

### ISSUE THREAD

**Issue by itcharlie** [tokuhirom/plenv#42]
$ plenv shell
plenv: no such command `shell'

This error can be fixed by addling a condition to change the command_path for plenv shell command. ( which should be plenv-sh-shell )

Example code in plenv file:

79   command_path="$(command -v "plenv-$command" ||  true)"
80   if [ -z "$command_path" ]; then

**Comment by miyagawa** [comment]
Closing as not reproducible.
