### ISSUE TITLE
Port to Fish shell

### ISSUE THREAD

**Issue by pwr22** [tokuhirom/plenv#75]
Fish is awesome, plenv is awesome, they should be awesome together!

**Comment by tokuhirom** [comment]
Hah. I haven't use fish... Contributes welcome.

**Comment by pwr22** [comment]
It isn't compatible with POSIX shells, would probably be a full rewrite :P

**Comment by syohex** [comment]
What benefits can we get from implementing plenv in fish ?

**Comment by pwr22** [comment]
@syohex People using fish can use it. Perlbrew currently has good fish support, for comparison

**Comment by syohex** [comment]
Sorry I misunderstand.

**Comment by syohex** [comment]
@pwr22 Please check latest version. You can initialize for fish with following command.

```fish
. (plenv init -|psub)
```

**Comment by pwr22** [comment]
Thanks, will give it a shot later

**Comment by miyagawa** [comment]
Close as implemented in #76.
