### ISSUE TITLE
plenv install docs wrong?

### ISSUE THREAD

**Issue by wolfsage** [tokuhirom/plenv#83]
```
For detailed information on installing Perl versions with
perl-build, including a list of environment variables for adjusting
compilation, see: https://github.com/tokuhirom/perl-build#usage
```

But https://github.com/tokuhirom/perl-build#usage doesn't actually have a usage section and I don't see environment variables mentioned anywhere.

What I'm looking for is how to pass my own args to Configure in plenv install.

Thanks!

**Comment by tokuhirom** [comment]
Fixed by #42
