### ISSUE TITLE
plenv overrides 'convert' command

### ISSUE THREAD

**Issue by dnmfarrell** [tokuhirom/plenv#84]
`convert` is an ImageMagick app installed in `/bin/convert`, but when plenv is installed, I get this error:

    $ convert
    plenv: convert: command not found

    The `convert' command exists in these Perl versions:
      5.18.4

I'm running Perl 5.20.2, Fedora 21.

**Comment by miyagawa** [comment]
plenv can override **any** executable that is installed by CPAN modules, and there's no way to special case or filter out such files.

You should uninstall the module that provides `convert` in your plenv's 5.18.4 installation.

**Comment by miyagawa** [comment]
I don't know what distribution has caused that, but even if you're not using plenv - using system perl or perlbrew - installing that module would clobber your $PATH with the convert command provided.

**Comment by dnmfarrell** [comment]
Ahh, I see, plenv creates a shim for any executable installed by a Perl module. Thanks!
