### ISSUE TITLE
Install without Git

### ISSUE THREAD

**Issue by ravenhall** [tokuhirom/plenv#86]
Need some instructions in the Install section on how to install without Git.

**Comment by tokuhirom** [comment]
p-r welcome

**Comment by SgtPooki** [comment]
There are homebrew instructions for mac. What other installation methods need described?

**Comment by sergeyromanov** [comment]
@SgtPooki I have a couple of CentOS boxes where I want to try `plenv` for managing multiple perl environments (no `git` executable there)

**Comment by SgtPooki** [comment]
So wget or curl instructions?

**Comment by Grinnz** [comment]
I submitted these instructions (using wget as example) in #114 and it was merged.

**Comment by sergeyromanov** [comment]
@Grinnz :+1:

**Comment by syohex** [comment]
Thanks @Grinnz
