### ISSUE TITLE
(XS) Modules installed by Carton doesn't play nice with Plenv

### ISSUE THREAD

**Issue by sharkyzz** [tokuhirom/plenv#90]
plenv global 5.23.0
plenv shell 5.23.0
plenv rehash

plenv versions
  system
* 5.23.0 (set by PLENV_VERSION environment variable)

carton install
....

carton exec perl app.pl 
Can't locate Data/Structure/Util.pm in @INC (you may need to install the Data::Structure::Util module) (@INC contains: /home/user/project/local/lib/perl5 /home/user/.plenv/versions/5.23.0/lib/perl5/site_perl/5.23.0/x86_64-linux-thread-multi /home/user/.plenv/versions/5.23.0/lib/perl5/site_perl/5.23.0 /home/user/.plenv/versions/5.23.0/lib/perl5/5.23.0/x86_64-linux-thread-multi /home/user/.plenv/versions/5.23.0/lib/perl5/5.23.0 .)

Although the module exists in my local lib, it isn't in my @INC.

ls /home/user/project/local/lib/perl5/x86_64-linux-gnu-thread-multi/Data/Structure/Util.pm     
/home/user/project/local/lib/perl5/x86_64-linux-gnu-thread-multi/Data/Structure/Util.pm

carton exec perl -e 'print "$_\n" for @INC'
/home/user/project/local/lib/perl5 
/home/user/.plenv/versions/5.23.0/lib/perl5/site_perl/5.23.0/x86_64-linux-thread-multi 
/home/user/.plenv/versions/5.23.0/lib/perl5/site_perl/5.23.0 
/home/user/.plenv/versions/5.23.0/lib/perl5/5.23.0/x86_64-linux-thread-multi 
/home/user/.plenv/versions/5.23.0/lib/perl5/5.23.0

So I thought add the extra lib dir to @INC

carton exec perl -I /home/user/project/local/lib/perl5/x86_64-linux-gnu-thread-multi app.pl
perl: symbol lookup error: /home/user/project/local/lib/perl5/x86_64-linux-gnu-thread-multi/auto/Data/Structure/Util/Util.so: undefined symbol: Perl_xs_apiversion_bootcheck

Using Perl installed by the system solves the problem

plenv global system
plenv shell system
plenv rehash

carton exec perl -e 'print "$_\n" for @INC'
/home/user/project/local/lib/perl5/x86_64-linux-gnu-thread-multi 
/home/user/project/local/lib/perl5 
/etc/perl 
/usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 
/usr/lib/perl5 
/usr/share/perl5 
/usr/lib/perl/5.14 
/usr/share/perl/5.14 
/usr/local/lib/site_perl

Now my application runs fine. So it seems that modules installed by Carton are compiled against my system perl instead of the one installed by plenv in my home directory.

**Comment by miyagawa** [comment]
>  So it seems that modules installed by Carton are compiled against my system perl instead of the one installed by plenv in my home directory.

That should not happen. You might either have 'perl` in your `$PATH` pointing to a wrong path (i.e. system perl) or  have a local::lib related environment variables set, affecting the installer to build and install modules using a wrong architecture.

Also, remove the `local` directory to start over Carton installation for each project. You can't switch versions once you build local directory with one version of perl.

I keep plenv with carton/carmel all the time and should not cause this problem.

**Comment by sharkyzz** [comment]
Please look into this:

$ plenv global
5.18.0
$ plenv shell 
5.18.0

$ cat cpanfile
requires 'SOAP::Lite';

One of the requirements of SOAP-Lite is Net-SSLeay. If I look into the cpanm buildlog

...
Running Mkbootstrap for Net::SSLeay ()
chmod 644 SSLeay.bs
/usr/bin/perl "-Iinc" /usr/share/perl/5.20/ExtUtils/xsubpp  -typemap /usr/share/perl/5.20/ExtUtils/typemap -typemap typemap  SSLeay.xs > SSLeay.xsc && mv SSLeay.xsc SSLeay.c
cc -c  -I/usr/include -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"1.70\" -DXS_VERSION=\"1.70\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.20/CORE"   SSLeay.c
rm -f blib/arch/auto/Net/SSLeay/SSLeay.so
cc  -shared -L/usr -L/usr/lib -L/usr/local/lib -fstack-protector SSLeay.o  -o blib/arch/auto/Net/SSLeay/SSLeay.so       \
   -L/usr -L/usr/lib -lssl -lcrypto -lz         \  
chmod 755 blib/arch/auto/Net/SSLeay/SSLeay.s
...

$ which cpanm
/home/developer/.plenv/shims/cpanm

$ env
SHELL=/bin/bash
TERM=xterm
OLDPWD=/home/developer
USER=developer
MAIL=/var/mail/developer
PATH=/home/developer/.plenv/shims:/home/developer/.plenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
PWD=/home/developer/Perlbot
PLENV_VERSION=5.18.0
SHLVL=1
HOME=/home/developer
PLENV_SHELL=bash
LOGNAME=developer
_=/usr/bin/env

$ perl -v
This is perl 5, version 18, subversion 0 (v5.18.0) built for x86_64-linux

$ /usr/bin/perl -v
This is perl 5, version 20, subversion 2 (v5.20.2) built for x86_64-linux-gnu-thread-multi

**Comment by sharkyzz** [comment]
Btw my last comment is based on a new install of Debian (8.1), so that's why the Perl versions differ from my initial comment. But the problem remains the same.

**Comment by miyagawa** [comment]
This has almost nothing to do with carton, and purely your plenv setup issue with cpanm.

You should be able to reproduce this without using carton at all, by just running `cpanm -L /tmp/xyz Net::SSLeay` and see where it gets installed to.

I think your shell setup is incomplete with plenv, and when you invoke a new shell `$PATH` gets reset to the one without `~/.plenv/shims` which makes cpanm unable to run `perl` from the right plenv path. 

If you're using `plenv shell` or some sort to localize the effect of plenv, that is not compatible to cpanm at all because it needs to invoke a new process via shell command when building a new module.
