### ISSUE TITLE
Compiling 32 bit perl under x86_64 (not a bug)

### ISSUE THREAD

**Issue by mpapec** [tokuhirom/plenv#95]
I have problem with

    plenv install 5.21.11 -Accflags="-m32 -march=i686" -Aldflags="-m32 -march=i686" -Alddlflags="-shared -m32 -march=i686" -Darchname=i686

after installing i686 libs

    yum -y install glibc-devel.i686 glibc-devel ibstdc++-devel.i686

/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7/libgcc_s.so when searching for -lgcc_s
/usr/bin/ld: cannot find -lgcc_s
collect2: ld returned 1 exit status

more info

    ld -lgcc_s --verbose
attempt to open /usr/x86_64-redhat-linux/lib64/libgcc_s.so failed
attempt to open /usr/x86_64-redhat-linux/lib64/libgcc_s.a failed
attempt to open /usr/local/lib64/libgcc_s.so failed
attempt to open /usr/local/lib64/libgcc_s.a failed
attempt to open /lib64/libgcc_s.so failed
attempt to open /lib64/libgcc_s.a failed
attempt to open /usr/lib64/libgcc_s.so failed
attempt to open /usr/lib64/libgcc_s.a failed
attempt to open /usr/x86_64-redhat-linux/lib/libgcc_s.so failed
attempt to open /usr/x86_64-redhat-linux/lib/libgcc_s.a failed
attempt to open /usr/lib64/libgcc_s.so failed
attempt to open /usr/lib64/libgcc_s.a failed
attempt to open /usr/local/lib/libgcc_s.so failed
attempt to open /usr/local/lib/libgcc_s.a failed
attempt to open /lib/libgcc_s.so failed
attempt to open /lib/libgcc_s.a failed
attempt to open /usr/lib/libgcc_s.so failed
attempt to open /usr/lib/libgcc_s.a failed

    locate libgcc
/lib64/libgcc_s-4.4.7-20120601.so.1
/lib64/libgcc_s.so.1
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/libgcc.a
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/libgcc_eh.a
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/libgcc_s.so
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/32/libgcc.a
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/32/libgcc_eh.a
/usr/lib/gcc/x86_64-redhat-linux/4.4.4/32/libgcc_s.so

**Comment by syohex** [comment]
Please install `libgcc.i686` package.

```
# yum install libgcc.i686
```

**Comment by mpapec** [comment]
@syohex thank you, it compiles great after the update!

yum install libgcc db4-devel gdbm-devel
yum install libgcc.i686 db4-devel.i686 gdbm-devel.i686
